services:
  db:
    container_name: MainDatabase
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chouaib
      POSTGRES_DB: test2
    ports:
      - "5432:5432"
    volumes:
      - postgresVOL:/var/lib/postgresql/data

  taskservice:
    container_name: taskService
    build: .
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:chouaib@db:5432/test2

volumes:
  postgresVOL:
