services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chouaib
      POSTGRES_DB: habit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data

  habitservice:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:chouaib@db:5432/habit"

volumes:
  postgres_data:
